rpi: barebox: version bump 2018.03.0 -> 2020.08.1
Update to the latest barebox version, which also has the side effect
that it can boot the newer Linux kernel (first bad Distrokit commit was
61b5ec910db2fe82a39f, 2019-05-06: "platform-rpi/v7a: kernel version bump
5.0 -> 5.1").

Enable regulator support to get around a build issue in the RPi board
code [1], and allow color by default on the console. Also enable
PINCTRL_BCM283X, since it was renamed from GPIO_BCM283X. For all other
settings, use their default value.

Add a patch to fix a build failure with the bcm2835 sdhci driver.

[1]: "rpi-common.c:462:8: error: implicit declaration of function
     'regulator_get_name'; did you mean 'regulator_enable'?
     [-Werror=implicit-function-declaration]", fixed upstream via
     <https://www.mail-archive.com/barebox@lists.infradead.org/msg36326.html>

Tested-by: Roland Hieber <rhi@pengutronix.de> on rpi1-b, rpi-zero-w
Signed-off-by: Roland Hieber <rhi@pengutronix.de>